import config from "../config.json" assert { type: "json" };

import ejs from 'ejs';
import view from "@fastify/view";
import compress from "@fastify/compress";
import html_minifier from "html-minifier";

async function register(app, options)
{
    /*----------------------------------COMPRESS----------------------------------*/
    await app.register(compress, { global: true, threshold: 1024 });
    


    
    /*----------------------------------EJS----------------------------------*/
    app.register(view, {
        engine: { ejs: ejs },
        production: config.stage != "testing",
        options:
        {
            async: false,
            views: [ options.views_directory ],
            useHtmlMinifier: config.stage != "testing" ? html_minifier : false,
            htmlMinifierOptions:
            {
                "caseSensitive": true,
                "collapseBooleanAttributes": true,
                "collapseInlineTagWhitespace": true,
                "collapseWhitespace": true,
                "conservativeCollapse": false,
                "continueOnParseError": false,
                "decodeEntities": true,
                "html5": true,
                "includeAutoGeneratedTags": true,
                "keepClosingSlash": false,
                "minifyCSS": true,
                "minifyJS": true,
                "minifyURLs": false,
                "preserveLineBreaks": false,
                "preventAttributesEscaping": false,
                "processConditionalComments": false,
                "processScripts": [],
                "quoteCharacter": "\"",
                "removeAttributeQuotes": false,
                "removeComments": true,
                "removeEmptyAttributes": true,
                "removeEmptyElements": false,
                "removeOptionalTags": false,
                "removeRedundantAttributes": false,
                "removeScriptTypeAttributes": true,
                "removeStyleLinkTypeAttributes": true,
                "removeTagWhitespace": false,
                "sortAttributes": true,
                "sortClassName": true,
                "trimCustomFragments": false,
                "useShortDoctype": true
            }
        },
        propertyName: "render",
        root: options.views_directory,
        includeViewExtension: false
    });
}

import plugin from 'fastify-plugin';
export default plugin(register, { name: 'response', encapsulate: false });